google:
  api_key: "YOUR_KEY"
  # use models/gemini-2.5-pro-preview-03-25 for stronger(albeit slower) model
  model: "models/gemini-2.5-flash-preview-04-17"
  thinking_budget: 0

openrouter:
  api_key: "YOUR_KEY"
  model: "qwen/qwen3-30b-a3b:free"

processing:
  # TODO: Количество прогонов
  chunk_size: 5000
  output_dir: "output_books"
  provider: "google"
  retry_if_failed: True

prompt: |
  **Инструкции**
  1. Исправь все орфографические ошибки и опечатки. В частности, слеш("/") означает трудный случай, где стоит или пробел, или ничего
  2. Исправь пунктуационные и грамматические ошибки, особое внимание уделяя сложным случаям, ётифицируй текст.
  3. Не меняй никакие имена/сленг/слова, в которых ты не уверен. Кроме случаев, когда это очевидно опечатка/неправильная автозамена, тогда исправляй.
  4. Не меняй ничего другого, не меняй обороты, даже если тебе кажется, что они выглядят криво - это авторский стиль. Не меняй дефисы/тире на другие символы.

  **Фрагмент текста**
  {text_chunk}

  **Дополнительно**
  1. Выполните задачу, указанную в основном запросе, над предоставленным текстовым фрагментом.
  2. Выведите только обработанный текстовый фрагмент, избегайте добавления каких-либо дополнительных вводных или заключительных утверждений.
  3. Не добавляйте/не удаляйте/не изменяйте пустые символы (разрывы строк, пробелы, табуляции и т. д.). Сохраняйте их в том виде, в каком они есть, включая края, перед тегами и т. д.
  4. НИКОГДА не добавляйте/не удаляйте/не изменяйте теги. Теги в фрагменте могут не иметь закрывающей/открывающей пары,
  это нормально: вам даётся не весь текст, а его фрагмент.
  5. НИКОГДА не добавляйте/не удаляйте/не изменяйте <RUN/> теги, они системные для формата DOCX.
  6. НИКОГДА не добавляйте/не удаляйте/не изменяйте системные символы: @, #, $, % и другие
heuristics:
  remove_commas: True
  replace_tags_with_placeholder: True