prompt: |
  **Инструкции**
  1. Исправьте все орфографические ошибки и опечатки.
  2. Исправьте пунктуационные и грамматические ошибки, особое внимание уделяя сложным случаям.
  3. Не меняйте имена/сленг/слова, в которых ты вы уверены. Не меняйте жаргонизмы.
  4. Не меняйте оформление прямой речи(включая строчные/заглавные буквы). Не меняйте выбор тире(длинное/короткое/дефис).
  5. Не меняйте ничего другого, не меняй обороты, даже если вам кажется, что они выглядят криво - это авторский стиль. Не соединяй предложения: в тексте может быть парцелляция, это нормально.
  6. Ётифицируйте текст.

  **Фрагмент текста**
  {text_chunk}

  **Дополнительно**
  1. Выполните задачу, указанную в основном запросе, над предоставленным текстовым фрагментом.
  2. Выведите только обработанный текстовый фрагмент, избегайте добавления каких-либо дополнительных вводных или заключительных утверждений.
  3. Сохраните исходный состав и порядок конструкций вида "(tag [X])".