gemini:
  api_key: "YOUR_KEY"
  # use models/gemini-2.5-pro-exp-03-25 for stronger(albeit slower) model
  # UPD: Now it redirects you to gemini-2.5-pro-exp-05-06 which got nerfed and now is barely better than 2.0-flash
  model: "models/gemini-2.0-flash"
  thinking_budget: 24000

openrouter:
  api_key: "YOUR_KEY"
  model: "gemini-2.0-flash-exp:free"

processing:
  chunk_size: 8000
  output_dir: "output_books"
  provider: "gemini"
  workers_amount: 100
  number_of_passes: 1
  retry_if_failed: True
  docx_merge_runs: True

prompt: |
  **Инструкции**
  1. Исправь все орфографические ошибки и опечатки.
  2. Исправь пунктуационные и грамматические ошибки, особое внимание уделяя сложным случаям.
  3. Не меняй никакие имена/сленг/слова, в которых ты не уверен. Кроме случаев, когда это очевидная опечатка/неправильная автозамена, тогда исправляй.
  4. Не меняй оформление прямой речи.
  5. Не меняй ничего другого, не меняй обороты, даже если тебе кажется, что они выглядят криво - это авторский стиль.

  **Фрагмент текста**
  {text_chunk}

  **Дополнительно**
  1. Выполните задачу, указанную в основном запросе, над предоставленным текстовым фрагментом.
  2. Выведите только обработанный текстовый фрагмент, избегайте добавления каких-либо дополнительных вводных или заключительных утверждений.
  3. Не добавляйте/не удаляйте/не изменяйте пустые символы (разрывы строк, пробелы, табуляции и т. д.). Сохраняйте их в том виде, в каком они есть, включая края, перед тегами и т. д.
  4. НИКОГДА не добавляйте/не удаляйте/не изменяйте теги. Теги в фрагменте могут не иметь закрывающей/открывающей пары,
  это нормально: вам даётся не весь текст, а его фрагмент. Если количество тегов в вашем ответе не будет совпадать
  с оригиналом, ответ принят не будет.
  5. НИКОГДА не добавляйте/не удаляйте/не изменяйте <RUN/> теги: они системные для формата DOCX.
  6. НИКОГДА не добавляйте/не удаляйте/не изменяйте системные символы: @, #, $, % и другие
heuristics:
  remove_commas: True
  replace_tags_with_placeholder: True