gemini:
  api_key: "YOUR_KEY"
  # use models/gemini-2.5-pro-exp-03-25 for stronger(albeit slower) model
  # UPD: Now it redirects you to gemini-2.5-pro-exp-05-06 which got nerfed and now is barely better than 2.0-flash
  model: "models/gemini-2.0-flash"
  thinking_budget: 24000

openrouter:
  api_key: "YOUR_KEY"
  model: "google/gemini-2.0-flash-exp:free"

processing:
  chunk_size: 8000
  output_dir: "output_books"
  provider: "gemini"
  workers_amount: 3
  number_of_passes: 1
  number_of_retries: 5
  docx_merge_runs: True

prompt: |
  **Инструкции**
  1. Исправьте все орфографические ошибки и опечатки.
  2. Исправьте пунктуационные и грамматические ошибки, особое внимание уделяя сложным случаям.
  3. Не меняйте имена/сленг/слова, в которых ты не уверен. Не меняй жаргонизмы.
  4. Не меняйте оформление прямой речи.
  5. Не меняйте ничего другого, не меняй обороты, даже если вам кажется, что они выглядят криво - это авторский стиль. Не соединяй предложения: в тексте может быть парцелляция, это нормально.

  **Фрагмент текста**
  {text_chunk}

  **Дополнительно**
  1. Выполните задачу, указанную в основном запросе, над предоставленным текстовым фрагментом.
  2. Выведите только обработанный текстовый фрагмент, избегайте добавления каких-либо дополнительных вводных или заключительных утверждений.
  3. НИКОГДА Не добавляйте/не удаляйте/не изменяйте теги. Теги в фрагменте могут не иметь закрывающей/открывающей пары,
  это нормально: вам даётся не весь текст, а его фрагмент. Если количество тегов в вашем ответе не будет совпадать
  с оригиналом, ответ принят не будет.
  4. НИКОГДА не добавляйте/не удаляйте/не изменяйте <RUN/> и <TAG/> теги: они системные для формата DOCX.
heuristics:
  remove_commas: False
  replace_tags_with_placeholder: True
  placeholder: "<image/>"