google:
  api_key: "YOUR_KEY"
  # use models/gemini-2.5-pro-exp-03-25 for stronger(albeit slower) model
  model: "models/gemini-2.0-flash"
  thinking_budget: 0

openrouter:
  api_key: "YOUR_KEY"
  model: "deepseek/deepseek-chat-v3-0324:free"

processing:
  chunk_size: 3000
  output_dir: "output_books"
  provider: "openrouter"
  workers_amount: 100
  number_of_passes: 1
  retry_if_failed: True
  temporary_file_saves: True

prompt: |
  **Инструкции**
  1. Исправь все орфографические ошибки и опечатки.
  2. Исправь пунктуационные и грамматические ошибки, особое внимание уделяя сложным случаям, ётифицируй текст.
  3. Не меняй никакие имена/сленг/слова, в которых ты не уверен. Кроме случаев, когда это очевидная опечатка/неправильная автозамена, тогда исправляй.
  4. Не меняй формат прямой речи(тире, кавычки и тд. В частности, не заменяй точки на запятые или наоборот).
  5. Не меняй ничего другого, не меняй обороты, даже если тебе кажется, что они выглядят криво - это авторский стиль. Не меняй дефисы/тире на другие символы.

  **Фрагмент текста**
  {text_chunk}

  **Дополнительно**
  1. Выполните задачу, указанную в основном запросе, над предоставленным текстовым фрагментом.
  2. Выведите только обработанный текстовый фрагмент, избегайте добавления каких-либо дополнительных вводных или заключительных утверждений.
  3. Не добавляйте/не удаляйте/не изменяйте пустые символы (разрывы строк, пробелы, табуляции и т. д.). Сохраняйте их в том виде, в каком они есть, включая края, перед тегами и т. д.
  4. НИКОГДА не добавляйте/не удаляйте/не изменяйте теги. Теги в фрагменте могут не иметь закрывающей/открывающей пары,
  это нормально: вам даётся не весь текст, а его фрагмент. Если количество тегов в вашем ответе не будет совпадать
  с оригиналом, ответ принят не будет.
  5. НИКОГДА не добавляйте/не удаляйте/не изменяйте <RUN/> теги, они системные для формата DOCX.
  6. НИКОГДА не добавляйте/не удаляйте/не изменяйте системные символы: @, #, $, % и другие
heuristics:
  remove_commas: True
  replace_tags_with_placeholder: True