services:
  website:
    build: 
      context: .
      dockerfile: WebsiteDockerfile
    ports:
      - "8000:8000"
  bot:
    build: 
      context: .
      dockerfile: BotDockerfile
    env_file:
      - .env